### ISSUE TITLE
the miRNA seq in output file is different to the input 

### ISSUE THREAD

**Issue by HuGang-c** [atulkakrana/sPARTA.github#11]
Hello, Thank for the software,

I found that in the out 'All.libs.validated.uniq.csv' file, the sequence of miRseq is different to my input file,

here is an example:
my input is 'TGGAGAAGCAGGGCACGTGCA'

then the output became 'TCGTACACGGGACGAAGAGGT', I find that they are nearly same when I reverse the output sequence, but they still not same.

and here are info from the output file:

miRseq: TCGTACACGGGACGAAGAGGT 

tarSeq: AGCTTGTGTCCTGCTTCTCCA

Mismatch: 3T4T12
 
I want to know why and what sPARTA do to the sequence, thanks

**Comment by rkweku** [comment]
Hello!

I'm glad to see that you are using sPARTA, but I'm sorry to see that you are having issues.

As sPARTA is coded, it should not be making any changes to your input sequences in this type of way. I can see that the miRseq and your input sequence are nearly identical when the input sequence is reversed. The first 16 bases are identical, but the final 5 bases are where there are differences. Is there a chance that there is another sequence in your input file that may be in the same family that is actually the proper hit? Because of strand stranding issues and such, I might expect to find one of the following sequences in your input file from the miRseq: TGGAGAAGCAGGGCACATGCT, AGCATGTGCCCTGCTTCTCCA, or ACCTCTTCGTCCCGTGTACGA. Could you confirm if any of these are in your input file?

Cheers,
Reza

**Comment by HuGang-c** [comment]
Thanks for quick reply,

yes, I find the sequence, TGGAGAAGCAGGGCACATGCT, and the name of this sequence is same with another, sorry for this mistake, I can get the right result with sPARTA when I change the name.

Thanks again, 
Hugang

**Comment by rkweku** [comment]
> Thanks for quick reply,
> 
> yes, I find the sequence, TGGAGAAGCAGGGCACATGCT, and the name of this sequence is same with another, sorry for this mistake, I can get the right result with sPARTA when I change the name.
> 
> Thanks again,
> Hugang

No need to apologize about this at all. I'm glad I could help. Please don't hesitate to ask if you have any other questions.
