### ISSUE TITLE
set -genomeFeature

### ISSUE THREAD

**Issue by shenweima** [atulkakrana/sPARTA.github#3]
Can set -genomeFeature as  0 and 1 at the same time?
`python3 sPARTA.py -genomeFile IWGSCv1.fa -annoType GTF -annoFile transctipts_merged.gtf -genomeFeature <0/1> -miRNAFile miRNA.fa -libs <SRR1197125.chopped.trimmed.processed.txt SRR1197126.chopped.trimmed.processed.txt > -tarPred -tarScore --tag2FASTA --map2DD --validate -minTagLen 18 -accel 10`
An error
**-bash: 0/1: No such file or directory.**
How to set?

**Comment by atulkakrana** [comment]
Hi Shenweima,

No you cannot run sPARTA in both genic and intergenic mode at same time. I would suggest run one (genomeFeature = 0) and rename the folders - 'predicted' and 'output' and then run other ( genomeFeature = 1). 

The error is because you have to remove <> from your command. These are used to indicate where an input is required from user. For example, the command to identify genic targets of your miRNAs would be: 

`python3 sPARTA.py -genomeFile IWGSCv1.fa -annoType GTF -annoFile transctipts_merged.gtf -genomeFeature 0 -miRNAFile miRNA.fa -libs SRR1197125.chopped.trimmed.processed.txt SRR1197126.chopped.trimmed.processed.txt -tarPred -tarScore --tag2FASTA --map2DD --validate -minTagLen 18 -accel 10`

Best

Atul

**Comment by shenweima** [comment]
Thank you .
`python3 sPARTA.py -genomeFile IWGSCv1.fa -annoType GTF -annoFile transctipts_merged.gtf -genomeFeature 0 -miRNAFile miRNA.fa -libs SRR1197125.chopped.trimmed.processed.txt SRR1197126.chopped.trimmed.processed.txt -tarPred H -tarScore N --tag2FASTA --map2DD --validate -minTagLen 18 -accel 10`
